apiVersion: v1
kind: List
items:
 # Setup the permission required to read the config map
 - apiVersion: rbac.authorization.k8s.io/v1
   kind: RoleBinding
   metadata:
     name: role-view-default
   subjects:
    - kind: ServiceAccount
      name: default
   roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view

 - apiVersion: rbac.authorization.k8s.io/v1
   kind: RoleBinding
   metadata:
     name: role-view-jenkins
   subjects:
    - kind: ServiceAccount
      name: jenkins
   roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view

 # ConfigMap to be created to pass application.yml content to Spring Boot
 - apiVersion: v1
   kind: ConfigMap
   metadata:
     name: app-config
   data:
     application.yml: |
       # This properties file should be used to initialise a ConfigMap
       greeting:
         message: "Hello %s from a ConfigMap!"
